name: Remove old actions (7d)

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: # Pozwala na ręczne uruchomienie w dowolnym momencie z zakładki Actions

jobs:
  clean-history:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Usuń stare uruchomienia
        uses: AykutSarac/clean-workflow-runs@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          save_period: 7d
          retained_runs: 0