name: Remove old actions (7d)

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: # Pozwala na ręczne uruchomienie w dowolnym momencie z zakładki Actions

jobs:
  clean-logs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: igorjs/gh-actions-clean-workflow@v7
        with:
          token: ${{ secrets.GH_PAT }}
          runs_older_than: 7 # optional
          runs_to_keep: 3 # optional