name: Deploy Forecast to GitHub Pages

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 4 * * *'   # 06:00 Europe/Warsaw
    - cron: '0 7 * * 7'   # 09:00 Europe/Warsaw sunday
    - cron: '0 19 * * *'  # 21:00 Europe/Warsaw
    - cron: '30 20 * * *' # 22:30 Europe/Warsaw

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (main branch)
        uses: actions/checkout@v3

      - name: Fetch forecast.json from gh-pages if it exists
        run: |
          git fetch origin gh-pages
          mkdir -p public
          git show origin/gh-pages:forecast.json > forecast.json || echo "{}" > forecast.json

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install

      - name: Run forecast script
        run: python forecast.py

      - name: Debug output
        run: |
          echo "== Content of public/forecast_ha.json =="
          cat public/forecast_ha.json || echo "Plik nie znaleziony"
          echo "== Content of public/forecast.json =="
          cat public/forecast.json || echo "Plik nie znaleziony"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
